# Generated by Django 4.1.6 on 2023-03-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('IN_PROGRESS', 'В процессе'), ('DONE', 'Выполнено')], default='NEW', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='task_type',
            field=models.CharField(choices=[('TASK', 'Задача'), ('BUG', 'Ошибка'), ('Enhancement', 'Улучшение')], default='TASK', max_length=20, verbose_name='Тип задачи'),
        ),
    ]
