# Generated by Django 4.1.6 on 2023-03-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_tag_articletag_comment_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='article', through='todo.ArticleTag', to='todo.tag'),
        ),
    ]
