# Generated by Django 4.1.6 on 2023-03-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_todolist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='memo',
            field=models.TextField(blank=True, verbose_name='Текст дела'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
    ]
