# Generated by Django 4.1.6 on 2023-03-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_alter_todolist_memo_alter_todolist_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='important',
            field=models.BooleanField(default=False, verbose_name='Важность дела для вас'),
        ),
    ]
