# Generated by Django 4.1.6 on 2023-03-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_alter_todolist_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания напоминания'),
        ),
    ]
