# Generated by Django 4.1.6 on 2023-03-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_alter_todolist_date_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='date_deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
    ]
